INPUT = main02.cpp
OUTPUT = bin\main02
#MINGW32LIB = -LC:\wy-dev\sdl2-mingw-32\lib

# NOTE:
# - EXE requires dlls in the same folder to run.
# - run `main.exe > log.txt` to log errors

# This is the target that compiles our executable
all : $(INPUT)
	g++ -g $(INPUT) -static -o $(OUTPUT)

# C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\include
# C:\Program Files (x86)\Microsoft SDKs\Windows\v7.0A\Include